// frontend-vue/src/components/AccountSetup.vue
<template>
  <section class="account-screen">
    <div class="account-entry">
      <aside class="account-brand">
        <p class="eyebrow">{{ t('brand') }}</p>
        <h1>{{ t('tagline') }}</h1>
        <p>
          Vue 3 版本的前端，保留登入、聊天室與管理頁的核心結構，並直接接到現有 Go 後端。
        </p>
        <div class="account-feature-list">
          <span>Vue 3</span>
          <span>Vite</span>
          <span>WebSocket</span>
          <span>Admin console</span>
        </div>
      </aside>

      <div class="account-panel">
        <div class="account-panel-heading">
          <span>{{ modeLabel }}</span>
          <h2>{{ mode === 'create' ? t('createAccount') : t('signIn') }}</h2>
          <p class="account-copy">
            {{ mode === 'create' ? '建立新的顯示名稱後即可進入聊天室。' : '輸入既有顯示名稱直接登入。' }}
          </p>
        </div>

        <div class="account-mode-switch">
          <button
            type="button"
            :class="{ 'account-mode-active': mode === 'create' }"
            @click="mode = 'create'"
          >
            {{ t('createAccount') }}
          </button>
          <button
            type="button"
            :class="{ 'account-mode-active': mode === 'login' }"
            @click="mode = 'login'"
          >
            {{ t('signIn') }}
          </button>
        </div>

        <form class="account-form" @submit.prevent="submit">
          <label class="account-field">
            <span>{{ t('displayName') }}</span>
            <input
              v-model="displayName"
              autocomplete="nickname"
              :placeholder="t('displayNameHint')"
              :disabled="isSubmitting"
            />
          </label>

          <p v-if="error" class="account-message account-message-error">
            {{ t('errorPrefix') }} {{ error }}
          </p>
          <p v-else-if="showWakeHint" class="account-message account-message-info">
            {{ t('wakingBackend') }}
          </p>

          <button class="account-submit" type="submit" :disabled="isSubmitting || !displayName.trim()">
            {{ isSubmitting ? t('working') : actionLabel }}
          </button>
        </form>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from '../i18n'

const props = defineProps<{
  isSubmitting: boolean
  showWakeHint: boolean
  error: string
}>()

const emit = defineEmits<{
  (event: 'create', displayName: string): void
  (event: 'login', displayName: string): void
}>()

const { t } = useI18n()
const mode = ref<'create' | 'login'>('create')
const displayName = ref('')

const modeLabel = computed(() => (mode.value === 'create' ? t('createAccount') : t('signIn')))
const actionLabel = computed(() => (mode.value === 'create' ? t('submitCreate') : t('submitSignIn')))

const submit = () => {
  const name = displayName.value.trim()
  if (!name || props.isSubmitting) return

  if (mode.value === 'create') {
    emit('create', name)
    return
  }

  emit('login', name)
}
</script>

// frontend-react/src/components/account/AccountSetup.tsx
import { zodResolver } from '@hookform/resolvers/zod'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { useTranslation } from 'react-i18next'
import { z } from 'zod'

type AccountMode = 'login' | 'create'

type AccountSetupProps = {
  isSubmitting: boolean
  showWakeHint?: boolean
  error?: string
  onCreate: (displayName: string) => void
  onLogin: (displayName: string) => void
}

const accountSchema = z.object({
  displayName: z.string().trim().min(1).max(32),
})

type AccountFormValues = z.infer<typeof accountSchema>

export default function AccountSetup({
  isSubmitting,
  showWakeHint = false,
  error = '',
  onCreate,
  onLogin,
}: AccountSetupProps) {
  const { t } = useTranslation()
  const [mode, setMode] = useState<AccountMode>('login')
  const {
    formState: { errors },
    handleSubmit,
    register,
    watch,
  } = useForm<AccountFormValues>({
    resolver: zodResolver(accountSchema),
    defaultValues: {
      displayName: '',
    },
  })
  const displayName = watch('displayName')

  const submit = handleSubmit(({ displayName: rawDisplayName }) => {
    const name = rawDisplayName.trim()
    if (mode === 'login') {
      onLogin(name)
      return
    }

    onCreate(name)
  })

  return (
    <main className="account-screen">
      <section className="account-entry" aria-label={t('account.brandName')}>
        <div className="account-brand">
          <p className="eyebrow">{t('account.eyebrow')}</p>
          <h1>{t('account.brandName')}</h1>
          <p>{t('account.brandCopy')}</p>
          <div className="account-feature-list" aria-label={t('account.featuresLabel')}>
            <span>{t('account.features.chat')}</span>
            <span>{t('account.features.market')}</span>
            <span>{t('account.features.realtime')}</span>
          </div>
        </div>

        <form className="account-panel" onSubmit={submit}>
          <div className="account-panel-heading">
            <span>{t('account.panelKicker')}</span>
            <h2>{t(`account.title.${mode}`)}</h2>
            <p className="account-copy">{t(`account.copy.${mode}`)}</p>
          </div>

          <div className="account-mode-switch" role="tablist" aria-label={t('account.modeLabel')}>
            <button
              type="button"
              className={mode === 'login' ? 'account-mode-active' : ''}
              onClick={() => setMode('login')}
            >
              {t('account.login')}
            </button>
            <button
              type="button"
              className={mode === 'create' ? 'account-mode-active' : ''}
              onClick={() => setMode('create')}
            >
              {t('account.create')}
            </button>
          </div>

          <label className="account-field">
            <span>{t('account.displayName')}</span>
            <input
              {...register('displayName')}
              type="text"
              maxLength={32}
              placeholder={t('account.placeholder')}
              autoComplete="nickname"
              autoFocus
            />
          </label>

          {errors.displayName ? (
            <p className="account-message account-message-error">{t('account.errors.displayNameRequired')}</p>
          ) : null}
          {error ? <p className="account-message account-message-error">{error}</p> : null}
          {!error && showWakeHint ? (
            <p className="account-message account-message-info">{t('account.wakeHint')}</p>
          ) : null}

          <button className="account-submit" type="submit" disabled={isSubmitting || !displayName?.trim()}>
            {isSubmitting
              ? t('account.submitting')
              : mode === 'login'
                ? t('account.login')
                : t('account.submitCreate')}
          </button>
        </form>
      </section>
    </main>
  )
}
