// frontend-vue/src/components/LanguageSwitcher.vue
<template>
  <div class="language-switcher" :aria-label="t('language')">
    <button
      type="button"
      :class="{ 'language-switcher-active': locale === 'zh' }"
      @click="setLocale('zh')"
    >
      中文
    </button>
    <button
      type="button"
      :class="{ 'language-switcher-active': locale === 'en' }"
      @click="setLocale('en')"
    >
      EN
    </button>
  </div>
</template>

<script setup lang="ts">
import { useI18n } from '../i18n'

const { locale, setLocale, t } = useI18n()
</script>

// frontend-react/src/components/LanguageSwitcher.jsx
import { useTranslation } from 'react-i18next'

const LOCALES = [
  { label: 'ZH', value: 'zh-TW' },
  { label: 'EN', value: 'en' },
]

export default function LanguageSwitcher() {
  const { i18n } = useTranslation()

  const switchLanguage = (language) => {
    i18n.changeLanguage(language)
    window.localStorage.setItem('yuna-im-locale', language)
  }

  return (
    <div className="language-switcher" aria-label="Language selector">
      {LOCALES.map((locale) => (
        <button
          key={locale.value}
          type="button"
          className={i18n.language === locale.value ? 'language-switcher-active' : ''}
          aria-pressed={i18n.language === locale.value}
          onClick={() => switchLanguage(locale.value)}
        >
          {locale.label}
        </button>
      ))}
    </div>
  )
}
