// frontend-react/src/components/chat/MessageList.jsx
import { useEffect, useMemo, useRef } from 'react'
import { useTranslation } from 'react-i18next'
import MessageBubble from './MessageBubble.jsx'

const parseMessageDate = (value) => {
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? new Date() : date
}

const dateKey = (value) => {
  const date = parseMessageDate(value)
  return `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`
}

const formatDateLabel = (value, t, language) => {
  const date = parseMessageDate(value)
  const today = new Date()
  const yesterday = new Date()
  yesterday.setDate(today.getDate() - 1)

  if (dateKey(value) === dateKey(today)) return t('chat.today')
  if (dateKey(value) === dateKey(yesterday)) return t('chat.yesterday')

  const sameYear = date.getFullYear() === today.getFullYear()
  return date.toLocaleDateString(language, {
    year: sameYear ? undefined : 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

export default function MessageList({ messages, activeRoom }) {
  const { i18n, t } = useTranslation()
  const messageList = useRef(null)
  const messageEnd = useRef(null)
  const messageItems = useMemo(() => {
    const items = []
    let previousDateKey = ''

    messages.forEach((message, index) => {
      const currentDateKey = dateKey(message.sentAt)
      if (currentDateKey !== previousDateKey) {
        items.push({
          type: 'date',
          key: `date-${currentDateKey}-${index}`,
          label: formatDateLabel(message.sentAt, t, i18n.language),
        })
        previousDateKey = currentDateKey
      }

      items.push({
        type: 'message',
        key: `${message.sender}-${message.sentAt}-${index}`,
        message,
      })
    })

    return items
  }, [i18n.language, messages, t])

  useEffect(() => {
    requestAnimationFrame(() => {
      messageEnd.current?.scrollIntoView({ block: 'end' })

      if (messageList.current) {
        messageList.current.scrollTop = messageList.current.scrollHeight
      }
    })
  }, [messages.length])

  return (
    <section ref={messageList} className="message-list" aria-live="polite">
      {messages.length === 0 ? <p className="empty-state">{activeRoom.description}</p> : null}

      {messageItems.map((item) =>
        item.type === 'date' ? (
          <div key={item.key} className="message-date-divider">
            {item.label}
          </div>
        ) : (
          <MessageBubble key={item.key} message={item.message} />
        ),
      )}

      <div ref={messageEnd} className="message-end" aria-hidden="true" />
    </section>
  )
}

// frontend-vue/src/components/chat/MessageList.vue
<script setup>
import { computed, nextTick, ref, watch } from 'vue'
import MessageBubble from './MessageBubble.vue'

const props = defineProps({
  messages: {
    type: Array,
    required: true,
  },
  activeRoom: {
    type: Object,
    required: true,
  },
})

const messageList = ref(null)
const messageEnd = ref(null)

const parseMessageDate = (value) => {
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? new Date() : date
}

const dateKey = (value) => {
  const date = parseMessageDate(value)
  return `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`
}

const formatDateLabel = (value) => {
  const date = parseMessageDate(value)
  const today = new Date()
  const yesterday = new Date()
  yesterday.setDate(today.getDate() - 1)

  if (dateKey(value) === dateKey(today)) return '今天'
  if (dateKey(value) === dateKey(yesterday)) return '昨天'

  const sameYear = date.getFullYear() === today.getFullYear()
  return date.toLocaleDateString('zh-TW', {
    year: sameYear ? undefined : 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

const messageItems = computed(() => {
  const items = []
  let previousDateKey = ''

  props.messages.forEach((message, index) => {
    const currentDateKey = dateKey(message.sentAt)
    if (currentDateKey !== previousDateKey) {
      items.push({
        type: 'date',
        key: `date-${currentDateKey}-${index}`,
        label: formatDateLabel(message.sentAt),
      })
      previousDateKey = currentDateKey
    }

    items.push({
      type: 'message',
      key: `${message.sender}-${message.sentAt}-${index}`,
      message,
    })
  })

  return items
})

const scrollToLatest = async () => {
  await nextTick()

  requestAnimationFrame(() => {
    messageEnd.value?.scrollIntoView({ block: 'end' })

    if (messageList.value) {
      messageList.value.scrollTop = messageList.value.scrollHeight
    }
  })
}

watch(
  () => props.messages.length,
  () => {
    scrollToLatest()
  },
  { flush: 'post' },
)
</script>

<template>
  <section ref="messageList" class="message-list" aria-live="polite">
    <p v-if="messages.length === 0" class="empty-state">
      {{ activeRoom.description }}
    </p>

    <template v-for="item in messageItems" :key="item.key">
      <div v-if="item.type === 'date'" class="message-date-divider">
        {{ item.label }}
      </div>
      <MessageBubble v-else :message="item.message" />
    </template>

    <div ref="messageEnd" class="message-end" aria-hidden="true"></div>
  </section>
</template>
