// frontend-vue/src/components/chat/ChatHeader.vue
<script setup>
defineProps({
  isConnected: {
    type: Boolean,
    required: true,
  },
  room: {
    type: Object,
    required: true,
  },
})

defineEmits(['back'])
</script>

<template>
  <header class="chat-header">
    <div class="chat-header-main">
      <button type="button" class="chat-back-button" aria-label="返回聊天列表" @click="$emit('back')">
        ‹
      </button>
      <div>
        <p class="eyebrow">Direct Message</p>
        <h1>{{ room.name }}</h1>
      </div>
    </div>
    <span class="status" :class="{ 'status-connected': isConnected }">
      {{ isConnected ? '已連線' : '未連線' }}
    </span>
  </header>
</template>

// frontend-react/src/components/chat/ChatHeader.jsx
export default function ChatHeader({ isConnected, room, onBack }) {
  return (
    <header className="chat-header">
      <div className="chat-header-main">
        <button type="button" className="chat-back-button" aria-label="返回聊天列表" onClick={onBack}>
          ‹
        </button>
        <div>
          <p className="eyebrow">Direct Message</p>
          <h1>{room.name}</h1>
        </div>
      </div>
      <span className={`status ${isConnected ? 'status-connected' : ''}`}>
        {isConnected ? '已連線' : '未連線'}
      </span>
    </header>
  )
}
