// frontend-vue/src/components/chat/ChatWindow.vue
<script setup>
import { onMounted, onUnmounted, ref } from 'vue'
import { useChatViewModel } from '../../composables/useChatViewModel'
import ChatComposer from './ChatComposer.vue'
import ChatHeader from './ChatHeader.vue'
import MessageList from './MessageList.vue'
import RoomList from './RoomList.vue'

const props = defineProps({
  currentUser: {
    type: Object,
    required: true,
  },
})

const emit = defineEmits(['logout'])
const mobileView = ref('rooms')
let wasMobile = false

const {
  rooms,
  availableUsers,
  activeRoom,
  activeRoomId,
  messages,
  userInput,
  fileAttachment,
  isConnected,
  connectionError,
  roomError,
  canSend,
  selectRoom,
  startChatWithUser,
  addFriend,
  attachFile,
  clearFileAttachment,
  refreshFriends,
  sendMessage,
} = useChatViewModel(props.currentUser)

const openRoom = (roomId) => {
  selectRoom(roomId)
  mobileView.value = 'chat'
}

const openUserChat = (user) => {
  startChatWithUser(user)
  mobileView.value = 'chat'
}

const syncMobileView = () => {
  const isMobile = window.matchMedia('(max-width: 768px)').matches
  if (isMobile && !wasMobile) {
    mobileView.value = 'chat'
  }
  wasMobile = isMobile
}

onMounted(() => {
  wasMobile = window.matchMedia('(max-width: 768px)').matches
  window.addEventListener('resize', syncMobileView)
})

onUnmounted(() => {
  window.removeEventListener('resize', syncMobileView)
})
</script>

<template>
  <main
    class="chat-shell"
    :class="{
      'chat-shell-mobile-list': mobileView === 'rooms',
      'chat-shell-mobile-chat': mobileView === 'chat',
    }"
  >
    <RoomList
      :rooms="rooms"
      :available-users="availableUsers"
      :active-room-id="activeRoomId"
      :error="roomError"
      :current-user="props.currentUser"
      @select="openRoom"
      @start-chat="openUserChat"
      @add-friend="addFriend"
      @refresh-friends="refreshFriends"
      @logout="emit('logout')"
    />

    <section class="chat-panel">
      <ChatHeader
        :is-connected="isConnected"
        :room="activeRoom"
        @back="mobileView = 'rooms'"
      />

      <p v-if="connectionError" class="connection-error">
        {{ connectionError }}
      </p>

      <MessageList :messages="messages" :active-room="activeRoom" />

      <ChatComposer
        v-model="userInput"
        :file-attachment="fileAttachment"
        :allow-attachments="activeRoom.id !== 'stock_bot'"
        :can-send="canSend"
        :placeholder="
          activeRoom.id === 'stock_bot'
            ? '輸入股票代號，例如 2330、$TSM...'
            : `傳訊息給 ${activeRoom.name}...`
        "
        :submit-label="activeRoom.id === 'stock_bot' ? '分析' : '送出'"
        @attach-file="attachFile"
        @clear-file="clearFileAttachment"
        @send="sendMessage"
      />
    </section>
  </main>
</template>

// frontend-react/src/components/chat/ChatWindow.tsx
import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useChatViewModel } from '../../hooks/useChatViewModel'
import ChatComposer from './ChatComposer.jsx'
import ChatHeader from './ChatHeader'
import MessageList from './MessageList.jsx'
import RoomList from './RoomList.jsx'
import VoiceCallBar from './VoiceCallBar.jsx'
import { useChatUiStore } from '../../stores/chatUiStore'
import type { ApiUser, ChatRoom, CurrentUser } from '../../types/chat'

type ChatWindowProps = {
  currentUser: CurrentUser
  onLogout: () => void
}

export default function ChatWindow({ currentUser, onLogout }: ChatWindowProps) {
  const { t } = useTranslation()
  const mobileView = useChatUiStore((state) => state.mobileView)
  const setMobileView = useChatUiStore((state) => state.setMobileView)
  const [wasMobile, setWasMobile] = useState(() => window.matchMedia('(max-width: 768px)').matches)
  const {
    rooms,
    availableUsers,
    activeRoom,
    activeRoomId,
    messages,
    userInput,
    setUserInput,
    fileAttachment,
    isConnected,
    connectionError,
    roomError,
    canSend,
    isStockBotPending,
    voiceCall,
    setRemoteAudioElement,
    selectRoom,
    startChatWithUser,
    addFriend,
    deleteFriend,
    createGroup,
    leaveGroup,
    attachFile,
    clearFileAttachment,
    refreshFriends,
    sendMessage,
    startVoiceCall,
    acceptVoiceCall,
    rejectVoiceCall,
    endVoiceCall,
    toggleVoiceMute,
  } = useChatViewModel(currentUser)
  const typedActiveRoom = activeRoom as ChatRoom

  const openRoom = (roomId: string) => {
    selectRoom(roomId)
    setMobileView('chat')
  }

  const openUserChat = (user: ApiUser) => {
    startChatWithUser(user)
    setMobileView('chat')
  }

  const activeRoomMemberNames = useMemo(() => {
    if (!typedActiveRoom?.isGroup) return []

    const namesById = new Map([[currentUser.id, currentUser.displayName]])
    availableUsers.forEach((user: ApiUser) => {
      namesById.set(user.user_id, user.display_name)
    })

    return (typedActiveRoom.memberIds || []).map((memberId: string) => namesById.get(memberId) || memberId)
  }, [typedActiveRoom, availableUsers, currentUser.displayName, currentUser.id])

  useEffect(() => {
    const syncMobileView = () => {
      const isMobile = window.matchMedia('(max-width: 768px)').matches
      if (isMobile && !wasMobile) {
        setMobileView('chat')
      }
      setWasMobile(isMobile)
    }

    window.addEventListener('resize', syncMobileView)
    return () => {
      window.removeEventListener('resize', syncMobileView)
    }
  }, [wasMobile])

  return (
    <main
      className={`chat-shell ${
        mobileView === 'rooms' ? 'chat-shell-mobile-list' : 'chat-shell-mobile-chat'
      }`}
    >
      <RoomList
        rooms={rooms}
        availableUsers={availableUsers}
        activeRoomId={activeRoomId}
        error={roomError}
        currentUser={currentUser}
        onSelect={openRoom}
        onStartChat={openUserChat}
        onAddFriend={addFriend}
        onDeleteFriend={deleteFriend}
        onCreateGroup={createGroup}
        onRefreshFriends={refreshFriends}
        onLogout={onLogout}
      />

      <section className="chat-panel">
        <ChatHeader
          isConnected={isConnected}
          room={typedActiveRoom}
          memberNames={activeRoomMemberNames}
          canStartVoiceCall={typedActiveRoom.id !== 'stock_bot' && !typedActiveRoom.isGroup && voiceCall.status === 'idle'}
          onBack={() => setMobileView('rooms')}
          onLeaveGroup={() => leaveGroup(typedActiveRoom.id)}
          onStartVoiceCall={startVoiceCall}
        />

        {connectionError ? <p className="connection-error">{connectionError}</p> : null}

        <VoiceCallBar
          voiceCall={voiceCall}
          onAccept={acceptVoiceCall}
          onReject={rejectVoiceCall}
          onEnd={endVoiceCall}
          onToggleMute={toggleVoiceMute}
          remoteAudioRef={setRemoteAudioElement}
        />

        <MessageList
          messages={messages}
          activeRoom={typedActiveRoom}
          isStockBotPending={isStockBotPending}
          onQuickStockQuery={sendMessage}
        />

        <ChatComposer
          value={userInput}
          onChange={setUserInput}
          fileAttachment={fileAttachment}
          allowAttachments={typedActiveRoom.id !== 'stock_bot'}
          variant={typedActiveRoom.id === 'stock_bot' ? 'stock' : 'chat'}
          canSend={canSend}
          placeholder={
            typedActiveRoom.id === 'stock_bot'
              ? t('chat.stockPlaceholder')
              : t('chat.messagePlaceholder', { name: typedActiveRoom.name })
          }
          submitLabel={typedActiveRoom.id === 'stock_bot' ? t('chat.query') : t('chat.send')}
          onAttachFile={attachFile}
          onClearFile={clearFileAttachment}
          onSend={sendMessage}
        />
      </section>
    </main>
  )
}
