// frontend-vue/src/components/chat/ChatWindow.vue
<script setup>
import { onMounted, onUnmounted, ref } from 'vue'
import { useChatViewModel } from '../../composables/useChatViewModel'
import ChatComposer from './ChatComposer.vue'
import ChatHeader from './ChatHeader.vue'
import MessageList from './MessageList.vue'
import RoomList from './RoomList.vue'

const props = defineProps({
  currentUser: {
    type: Object,
    required: true,
  },
})

const emit = defineEmits(['logout'])
const mobileView = ref('rooms')
let wasMobile = false

const {
  rooms,
  availableUsers,
  activeRoom,
  activeRoomId,
  messages,
  userInput,
  isConnected,
  connectionError,
  roomError,
  canSend,
  selectRoom,
  startChatWithUser,
  addFriend,
  refreshFriends,
  sendMessage,
} = useChatViewModel(props.currentUser)

const openRoom = (roomId) => {
  selectRoom(roomId)
  mobileView.value = 'chat'
}

const openUserChat = (user) => {
  startChatWithUser(user)
  mobileView.value = 'chat'
}

const syncMobileView = () => {
  const isMobile = window.matchMedia('(max-width: 768px)').matches
  if (isMobile && !wasMobile) {
    mobileView.value = 'chat'
  }
  wasMobile = isMobile
}

onMounted(() => {
  wasMobile = window.matchMedia('(max-width: 768px)').matches
  window.addEventListener('resize', syncMobileView)
})

onUnmounted(() => {
  window.removeEventListener('resize', syncMobileView)
})
</script>

<template>
  <main
    class="chat-shell"
    :class="{
      'chat-shell-mobile-list': mobileView === 'rooms',
      'chat-shell-mobile-chat': mobileView === 'chat',
    }"
  >
    <RoomList
      :rooms="rooms"
      :available-users="availableUsers"
      :active-room-id="activeRoomId"
      :error="roomError"
      :current-user="props.currentUser"
      @select="openRoom"
      @start-chat="openUserChat"
      @add-friend="addFriend"
      @refresh-friends="refreshFriends"
      @logout="emit('logout')"
    />

    <section class="chat-panel">
      <ChatHeader
        :is-connected="isConnected"
        :room="activeRoom"
        @back="mobileView = 'rooms'"
      />

      <p v-if="connectionError" class="connection-error">
        {{ connectionError }}
      </p>

      <MessageList :messages="messages" :active-room="activeRoom" />

      <ChatComposer
        v-model="userInput"
        :can-send="canSend"
        :placeholder="
          activeRoom.id === 'stock_bot'
            ? '輸入股票代號，例如 2330、$TSM...'
            : `傳訊息給 ${activeRoom.name}...`
        "
        :submit-label="activeRoom.id === 'stock_bot' ? '分析' : '送出'"
        @send="sendMessage"
      />
    </section>
  </main>
</template>

// frontend-react/src/components/chat/ChatWindow.jsx
import { useEffect, useState } from 'react'
import { useChatViewModel } from '../../hooks/useChatViewModel'
import ChatComposer from './ChatComposer.jsx'
import ChatHeader from './ChatHeader.jsx'
import MessageList from './MessageList.jsx'
import RoomList from './RoomList.jsx'

export default function ChatWindow({ currentUser, onLogout }) {
  const [mobileView, setMobileView] = useState('rooms')
  const [wasMobile, setWasMobile] = useState(() => window.matchMedia('(max-width: 768px)').matches)
  const {
    rooms,
    availableUsers,
    activeRoom,
    activeRoomId,
    messages,
    userInput,
    setUserInput,
    fileAttachment,
    isConnected,
    connectionError,
    roomError,
    canSend,
    selectRoom,
    startChatWithUser,
    addFriend,
    attachFile,
    clearFileAttachment,
    refreshFriends,
    sendMessage,
  } = useChatViewModel(currentUser)

  const openRoom = (roomId) => {
    selectRoom(roomId)
    setMobileView('chat')
  }

  const openUserChat = (user) => {
    startChatWithUser(user)
    setMobileView('chat')
  }

  useEffect(() => {
    const syncMobileView = () => {
      const isMobile = window.matchMedia('(max-width: 768px)').matches
      if (isMobile && !wasMobile) {
        setMobileView('chat')
      }
      setWasMobile(isMobile)
    }

    window.addEventListener('resize', syncMobileView)
    return () => {
      window.removeEventListener('resize', syncMobileView)
    }
  }, [wasMobile])

  return (
    <main
      className={`chat-shell ${
        mobileView === 'rooms' ? 'chat-shell-mobile-list' : 'chat-shell-mobile-chat'
      }`}
    >
      <RoomList
        rooms={rooms}
        availableUsers={availableUsers}
        activeRoomId={activeRoomId}
        error={roomError}
        currentUser={currentUser}
        onSelect={openRoom}
        onStartChat={openUserChat}
        onAddFriend={addFriend}
        onRefreshFriends={refreshFriends}
        onLogout={onLogout}
      />

      <section className="chat-panel">
        <ChatHeader isConnected={isConnected} room={activeRoom} onBack={() => setMobileView('rooms')} />

        {connectionError ? <p className="connection-error">{connectionError}</p> : null}

        <MessageList messages={messages} activeRoom={activeRoom} />

        <ChatComposer
          value={userInput}
          onChange={setUserInput}
          fileAttachment={fileAttachment}
          allowAttachments={activeRoom.id !== 'stock_bot'}
          canSend={canSend}
          placeholder={
            activeRoom.id === 'stock_bot'
              ? '輸入股票代號，例如 2330、$TSM...'
              : `傳訊息給 ${activeRoom.name}...`
          }
          submitLabel={activeRoom.id === 'stock_bot' ? '分析' : '送出'}
          onAttachFile={attachFile}
          onClearFile={clearFileAttachment}
          onSend={sendMessage}
        />
      </section>
    </main>
  )
}
