// frontend-vue/src/components/chat/ChatHeader.vue
<script setup>
defineProps({
  isConnected: {
    type: Boolean,
    required: true,
  },
  room: {
    type: Object,
    required: true,
  },
})

defineEmits(['back'])
</script>

<template>
  <header class="chat-header">
    <div class="chat-header-main">
      <button type="button" class="chat-back-button" aria-label="返回聊天列表" @click="$emit('back')">
        ‹
      </button>
      <div>
        <p class="eyebrow">Direct Message</p>
        <h1>{{ room.name }}</h1>
      </div>
    </div>
    <span class="status" :class="{ 'status-connected': isConnected }">
      {{ isConnected ? '已連線' : '未連線' }}
    </span>
  </header>
</template>

// frontend-react/src/components/chat/ChatHeader.tsx
import { useTranslation } from 'react-i18next'
import type { ChatRoom } from '../../types/chat'

type ChatHeaderProps = {
  isConnected: boolean
  room: ChatRoom
  memberNames?: string[]
  canStartVoiceCall?: boolean
  onBack: () => void
  onLeaveGroup: () => void
  onStartVoiceCall: () => void
}

export default function ChatHeader({
  isConnected,
  room,
  memberNames = [],
  canStartVoiceCall = false,
  onBack,
  onLeaveGroup,
  onStartVoiceCall,
}: ChatHeaderProps) {
  const { t } = useTranslation()
  const isGroup = Boolean(room.isGroup)
  const eyebrow = isGroup ? t('chat.groupChat') : t('chat.directMessage')
  const memberSummary = isGroup ? memberNames.join(', ') : ''

  return (
    <header className="chat-header">
      <div className="chat-header-main">
        <button type="button" className="chat-back-button" aria-label={t('chat.backToRooms')} onClick={onBack}>
          ‹
        </button>
        <div className="chat-title-block">
          <p className="eyebrow">{eyebrow}</p>
          <h1>{room.name}</h1>
          {isGroup && memberSummary ? (
            <p className="chat-subtitle">{t('chat.groupMemberList', { members: memberSummary })}</p>
          ) : null}
        </div>
      </div>
      <div className="chat-header-actions">
        {canStartVoiceCall ? (
          <button type="button" className="voice-call-button" onClick={onStartVoiceCall}>
            {t('chat.voiceCall')}
          </button>
        ) : null}
        {isGroup ? (
          <button type="button" className="leave-group-button" onClick={onLeaveGroup}>
            {t('chat.leaveGroup')}
          </button>
        ) : null}
        <span className={`status ${isConnected ? 'status-connected' : ''}`}>
          {isConnected ? t('chat.connected') : t('chat.disconnected')}
        </span>
      </div>
    </header>
  )
}
