// frontend-vue/src/components/chat/MessageBubble.vue
<script setup>
import { computed, nextTick, ref } from 'vue'
import { getChangeClass } from '../../utils/stockChange'

const props = defineProps({
  message: {
    type: Object,
    required: true,
  },
})

const isSelf = computed(() => props.message.isSelf)
const changeClass = computed(() => getChangeClass(props.message))
const isPending = computed(() => Boolean(props.message.isPending))
const hasText = computed(() => Boolean(props.message.text))
const hasAttachment = computed(() => Boolean(props.message.attachmentUrl))
const isImageAttachment = computed(() => props.message.attachmentType?.startsWith('image/'))
const attachmentLabel = computed(() => props.message.attachmentName || '檔案')
const isImagePreviewOpen = ref(false)
const imagePreviewModal = ref(null)
const sentTime = computed(() => {
  const date = new Date(props.message.sentAt)
  if (Number.isNaN(date.getTime())) return props.message.sentAt || ''

  return date.toLocaleTimeString('zh-TW', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  })
})
const readStatusLabel = computed(() => {
  if (!isSelf.value) return ''
  return props.message.readAt ? '已讀' : '未讀'
})

const openImagePreview = async () => {
  isImagePreviewOpen.value = true
  await nextTick()
  imagePreviewModal.value?.focus()
}

const closeImagePreview = () => {
  isImagePreviewOpen.value = false
}
</script>

<template>
  <article class="message" :class="{ 'message-self': isSelf, 'message-pending': isPending }">
    <a
      v-if="hasAttachment && isImageAttachment"
      class="message-image-link"
      :href="message.attachmentUrl"
      :aria-label="attachmentLabel"
      @click.prevent="openImagePreview"
    >
      <img
        class="message-image"
        :src="message.attachmentUrl"
        :alt="attachmentLabel"
        loading="lazy"
      />
    </a>
    <a
      v-else-if="hasAttachment"
      class="message-file-link"
      :href="message.attachmentUrl"
      target="_blank"
      rel="noreferrer"
      :download="attachmentLabel"
    >
      <span class="message-file-icon" aria-hidden="true">檔</span>
      <span>{{ attachmentLabel }}</span>
    </a>
    <div v-if="isPending" class="typing-indicator" aria-label="股票機器人正在回覆">
      <span />
      <span />
      <span />
    </div>
    <p v-else-if="hasText" :class="changeClass">{{ message.text }}</p>
    <footer v-if="!isPending" class="message-footer">
      <time v-if="sentTime">{{ sentTime }}</time>
      <span
        v-if="isSelf"
        class="message-read-status"
        :class="{ 'message-read-status-read': message.readAt }"
        :aria-label="readStatusLabel"
        :title="readStatusLabel"
      >
        <span />
        <span v-if="message.readAt" />
      </span>
    </footer>
  </article>

  <Teleport to="body">
    <div
      v-if="isImagePreviewOpen"
      ref="imagePreviewModal"
      class="image-preview-modal"
      role="dialog"
      aria-modal="true"
      :aria-label="attachmentLabel"
      tabindex="0"
      @click.self="closeImagePreview"
      @keydown.esc="closeImagePreview"
    >
      <button
        type="button"
        class="image-preview-close"
        aria-label="關閉圖片預覽"
        title="關閉圖片預覽"
        @click="closeImagePreview"
      >
        ×
      </button>
      <img
        class="image-preview-full"
        :src="message.attachmentUrl"
        :alt="attachmentLabel"
      />
    </div>
  </Teleport>
</template>

// frontend-react/src/components/chat/MessageBubble.jsx
import { createPortal } from 'react-dom'
import { useEffect, useRef, useState } from 'react'
import { getChangeClass } from '../../utils/stockChange'

export default function MessageBubble({ message }) {
  const [isImagePreviewOpen, setIsImagePreviewOpen] = useState(false)
  const imagePreviewModal = useRef(null)
  const isSelf = Boolean(message.isSelf)
  const isPending = Boolean(message.isPending)
  const hasText = Boolean(message.text)
  const hasAttachment = Boolean(message.attachmentUrl)
  const isImageAttachment = message.attachmentType?.startsWith('image/')
  const attachmentLabel = message.attachmentName || '檔案'
  const changeClass = getChangeClass(message)
  const sentTime = (() => {
    const date = new Date(message.sentAt)
    if (Number.isNaN(date.getTime())) return message.sentAt || ''

    return date.toLocaleTimeString('zh-TW', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
    })
  })()
  const readStatusLabel = isSelf ? (message.readAt ? '已讀' : '未讀') : ''

  useEffect(() => {
    if (isImagePreviewOpen) {
      imagePreviewModal.current?.focus()
    }
  }, [isImagePreviewOpen])

  return (
    <>
      <article className={`message ${isSelf ? 'message-self' : ''} ${isPending ? 'message-pending' : ''}`}>
        {hasAttachment && isImageAttachment ? (
          <a
            className="message-image-link"
            href={message.attachmentUrl}
            aria-label={attachmentLabel}
            onClick={(event) => {
              event.preventDefault()
              setIsImagePreviewOpen(true)
            }}
          >
            <img
              className="message-image"
              src={message.attachmentUrl}
              alt={attachmentLabel}
              loading="lazy"
            />
          </a>
        ) : null}
        {hasAttachment && !isImageAttachment ? (
          <a
            className="message-file-link"
            href={message.attachmentUrl}
            target="_blank"
            rel="noreferrer"
            download={attachmentLabel}
          >
            <span className="message-file-icon" aria-hidden="true">
              檔
            </span>
            <span>{attachmentLabel}</span>
          </a>
        ) : null}
        {isPending ? (
          <div className="typing-indicator" aria-label="股票機器人正在回覆">
            <span />
            <span />
            <span />
          </div>
        ) : null}
        {!isPending && hasText ? <p className={changeClass}>{message.text}</p> : null}
        {!isPending ? (
          <footer className="message-footer">
            {sentTime ? <time>{sentTime}</time> : null}
            {isSelf ? (
              <span
                className={`message-read-status ${message.readAt ? 'message-read-status-read' : ''}`}
                aria-label={readStatusLabel}
                title={readStatusLabel}
              >
                <span />
                {message.readAt ? <span /> : null}
              </span>
            ) : null}
          </footer>
        ) : null}
      </article>

      {isImagePreviewOpen
        ? createPortal(
            <div
              ref={imagePreviewModal}
              className="image-preview-modal"
              role="dialog"
              aria-modal="true"
              aria-label={attachmentLabel}
              tabIndex="0"
              onClick={(event) => {
                if (event.target === event.currentTarget) setIsImagePreviewOpen(false)
              }}
              onKeyDown={(event) => {
                if (event.key === 'Escape') setIsImagePreviewOpen(false)
              }}
            >
              <button
                type="button"
                className="image-preview-close"
                aria-label="關閉圖片預覽"
                title="關閉圖片預覽"
                onClick={() => setIsImagePreviewOpen(false)}
              >
                ×
              </button>
              <img className="image-preview-full" src={message.attachmentUrl} alt={attachmentLabel} />
            </div>,
            document.body,
          )
        : null}
    </>
  )
}
